# Generated by Django 5.2.3 on 2025-06-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaSaber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Área do Saber')),
            ],
            options={
                'verbose_name': 'Área do Saber',
                'verbose_name_plural': 'Áreas do Saber',
            },
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome da cidade')),
                ('uf', models.CharField(max_length=2, verbose_name='UF')),
            ],
            options={
                'verbose_name': 'Cidade',
                'verbose_name_plural': 'Cidades',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Tipo de Documento',
                'verbose_name_plural': 'Tipos de Documento',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('email', models.EmailField(max_length=100, verbose_name='Email')),
                ('senha', models.CharField(max_length=128, verbose_name='Senha')),
                ('perfil', models.CharField(choices=[('estudante', 'Estudante'), ('professor', 'Professor'), ('pesquisador', 'Pesquisador')], max_length=20, verbose_name='Perfil')),
            ],
            options={
                'verbose_name': 'Usuário',
                'verbose_name_plural': 'Usuários',
            },
        ),
        migrations.CreateModel(
            name='EventoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Evento')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_fim', models.DateField(verbose_name='Data de Fim')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade', verbose_name='Cidade')),
            ],
            options={
                'verbose_name': 'Evento Histórico',
                'verbose_name_plural': 'Eventos Históricos',
            },
        ),
        migrations.CreateModel(
            name='LinhaDoTempo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Linha do Tempo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_final', models.DateField(verbose_name='Data Final')),
                ('eventos', models.ManyToManyField(to='app.eventohistorico', verbose_name='Eventos Históricos')),
            ],
            options={
                'verbose_name': 'Linha do Tempo',
                'verbose_name_plural': 'Linhas do Tempo',
            },
        ),
        migrations.CreateModel(
            name='PersonagemHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Personagem')),
                ('biografia', models.TextField(verbose_name='Biografia')),
                ('data_nasc', models.DateField(verbose_name='Data de Nascimento')),
                ('data_falecimento', models.DateField(blank=True, null=True, verbose_name='Data de Falecimento')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.cidade', verbose_name='Cidade Natal')),
            ],
            options={
                'verbose_name': 'Personagem Histórico',
                'verbose_name_plural': 'Personagens Históricos',
            },
        ),
        migrations.CreateModel(
            name='DocumentoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200, verbose_name='Título')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('data_documento', models.DateField(verbose_name='Data do Documento')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='documentos/', verbose_name='Imagem')),
                ('evento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.eventohistorico', verbose_name='Evento Histórico')),
                ('personagem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.personagemhistorico', verbose_name='Personagem Histórico')),
                ('tipo_documento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.tipodocumento', verbose_name='Tipo de Documento')),
            ],
            options={
                'verbose_name': 'Documento Histórico',
                'verbose_name_plural': 'Documentos Históricos',
            },
        ),
    ]
