# Generated by Django 5.2.3 on 2025-07-14 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_ocupacao_alter_usuario_options_remove_usuario_perfil_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='linhadotempo',
            options={'verbose_name': 'linha', 'verbose_name_plural': 'linhas'},
        ),
        migrations.AlterModelOptions(
            name='ocupacao',
            options={'verbose_name': 'Ocupacao', 'verbose_name_plural': 'Ocupacoes'},
        ),
        migrations.AddField(
            model_name='eventohistorico',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.areasaber', verbose_name='Área do Saber'),
        ),
    ]
