# Generated by Django 5.2.3 on 2025-07-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_linhadotempo_options_alter_ocupacao_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipodocumento',
            options={'verbose_name': 'Tipo', 'verbose_name_plural': 'Tipos'},
        ),
        migrations.AlterField(
            model_name='tipodocumento',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Tipo'),
        ),
    ]
